# Generated by Django 6.0.6 on 2026-07-01 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_teamgroup_alter_coach_shirt_size_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='team',
            constraint=models.UniqueConstraint(fields=('name', 'federation', 'year_founded'), name='unique_name_federation_founded'),
        ),
    ]
